/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Employee;
import model.EmployeeHistory;

/**
 *
 * @author Rishab
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    String filePath = "";
    EmployeeHistory empHistory;

    public ViewPanel(EmployeeHistory history) {
        initComponents();
        empHistory = history;
        populateEmployeeTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblView = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        lblPosition = new javax.swing.JLabel();
        txtTeamInfo = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        lblMobile = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        txtLevel = new javax.swing.JTextField();
        lblTeamInfo = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        comboGender = new javax.swing.JComboBox<>();
        txtEmpId = new javax.swing.JTextField();
        lblEmpId = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        lblUploadSuccessful = new javax.swing.JLabel();

        lblView.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblView.setText("View Employee");
        lblView.setToolTipText("");

        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Employee ID", "Age", "Gender", "Start Date", "Level", "Team Info", "Position", "Mobile no", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEmployees);

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnView.setText("View ");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        lblPosition.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPosition.setText("Position:");

        lblGender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGender.setText("Gender:");

        lblMobile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMobile.setText("Mobile Number :");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmail.setText("Email ID:");

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblName.setText("Name :");

        lblAge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAge.setText("Age :");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDate.setText("Start Date:");

        lblLevel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLevel.setText("Level:");

        lblTeamInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTeamInfo.setText("Team Information:");

        txtStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartDateActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        comboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a value", "Male", "Female", "Other" }));
        comboGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGenderActionPerformed(evt);
            }
        });

        txtEmpId.setEditable(false);

        lblEmpId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmpId.setText("Employee Id :");

        btnUpload.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpload.setText("Upload File");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(lblView)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUpload)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTeamInfo)
                            .addComponent(lblLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMobile)
                            .addComponent(lblEmail)
                            .addComponent(lblPosition))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblEmpId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblGender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMobile, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addComponent(txtPosition, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addComponent(txtTeamInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addComponent(txtLevel, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboGender, 0, 315, Short.MAX_VALUE)
                            .addComponent(txtStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                        .addComponent(txtAge)
                        .addComponent(txtEmpId)
                        .addComponent(txtName))
                    .addComponent(lblUploadSuccessful, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 118, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comboGender, txtAge, txtEmail, txtEmpId, txtLevel, txtMobile, txtName, txtPosition, txtStartDate, txtTeamInfo});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnUpload, lblAge, lblDate, lblEmail, lblEmpId, lblGender, lblLevel, lblMobile, lblName, lblPosition, lblTeamInfo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnView))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblName)
                        .addGap(10, 10, 10)
                        .addComponent(lblAge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEmpId)
                        .addGap(18, 18, 18)
                        .addComponent(lblGender)
                        .addGap(19, 19, 19)
                        .addComponent(lblDate)
                        .addGap(18, 18, 18)
                        .addComponent(lblLevel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTeamInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMobile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEmail)
                        .addGap(18, 18, 18)
                        .addComponent(lblPosition)
                        .addGap(26, 26, 26)
                        .addComponent(btnUpload))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lblUploadSuccessful, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comboGender, txtAge, txtEmail, txtEmpId, txtLevel, txtMobile, txtName, txtPosition, txtStartDate, txtTeamInfo});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblAge, lblDate, lblEmail, lblEmpId, lblGender, lblLevel, lblMobile, lblName, lblPosition, lblTeamInfo});

    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        clearAllTextFields();

        int selectRowIndex = tblEmployees.getSelectedRow();

        if (selectRowIndex < 0) {
            JOptionPane.showConfirmDialog(this, "Please select a row to delete");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblEmployees.getModel();
        Employee selectedEmp = (Employee) model.getValueAt(selectRowIndex, 0);

        empHistory.deleteEmployee(selectedEmp);

        JOptionPane.showMessageDialog(null, "Employee Deleted!");

        populateEmployeeTable();


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed

        int selectRowIndex = tblEmployees.getSelectedRow();

        if (selectRowIndex < 0) {
            JOptionPane.showConfirmDialog(this, "Please select a row to view the data");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblEmployees.getModel();
        Employee selectedEmp = (Employee) model.getValueAt(selectRowIndex, 0);

        txtName.setText(selectedEmp.getName());
        txtEmpId.setText(String.valueOf(selectedEmp.getEmpId()));
        txtAge.setText(String.valueOf(selectedEmp.getAge()));

        int index = 0;
        if (selectedEmp.getGender().equalsIgnoreCase("male")) {
            index = 1;
        } else if (selectedEmp.getGender().equalsIgnoreCase("female")) {
            index = 2;
        } else if (selectedEmp.getGender().equalsIgnoreCase("other")) {
            index = 3;
        }

        comboGender.setSelectedIndex(index);
        txtStartDate.setText(String.valueOf(selectedEmp.getStartDate()));
        txtLevel.setText(selectedEmp.getLevel());
        txtTeamInfo.setText(selectedEmp.getTeamInfo());
        txtPosition.setText(selectedEmp.getPositionTitle());
        txtMobile.setText(selectedEmp.getMobileNo());
        txtEmail.setText(selectedEmp.getEmail());

        SetProfilePhoto(selectedEmp.getPhoto());


    }//GEN-LAST:event_btnViewActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartDateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        int selectRowIndex = tblEmployees.getSelectedRow();

        if (selectRowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to update");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblEmployees.getModel();
        Employee selectedEmp = (Employee) model.getValueAt(selectRowIndex, 0);

        String name = txtName.getText();
        String ageTemp = txtAge.getText();
        String empId = txtEmpId.getText();
        String gender = comboGender.getSelectedItem().toString();
        String startDatetemp = txtStartDate.getText();
        String level = txtLevel.getText();
        String teamInfo = txtTeamInfo.getText();
        String position = txtPosition.getText();
        String phone = txtMobile.getText();
        String email = txtEmail.getText();

        //apply validations here
        boolean isValid = validateData();

        if (isValid) {

            selectedEmp.setAge(Integer.parseInt(ageTemp));
            selectedEmp.setName(name);
            selectedEmp.setEmpId(Integer.parseInt(empId));
            selectedEmp.setGender(gender);

            selectedEmp.setStartDate(startDatetemp);

            selectedEmp.setLevel(level);
            selectedEmp.setTeamInfo(teamInfo);
            selectedEmp.setMobileNo(phone);
            selectedEmp.setEmail(email);
            selectedEmp.setPositionTitle(position);
            selectedEmp.setPhoto(filePath);

            JOptionPane.showMessageDialog(null, "Employee updated");

            populateEmployeeTable();

            txtName.setText("");
            txtAge.setText("");
            txtEmail.setText("");
            txtEmpId.setText("");
            txtStartDate.setText("");
            txtLevel.setText("");
            txtTeamInfo.setText("");
            txtMobile.setText("");
            txtEmail.setText("");
            txtPosition.setText("");
            comboGender.setSelectedIndex(0);
            lblPhoto.setText("");
            
            lblUploadSuccessful.setText("");

        }


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void comboGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGenderActionPerformed

    }//GEN-LAST:event_comboGenderActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed

        JFileChooser filePicker = new JFileChooser();
        filePicker.showOpenDialog(null);
        File file = filePicker.getSelectedFile();
        filePath = file.getAbsolutePath();

        if (filePath.equals("")) {
            lblUploadSuccessful.setText("Not able to upload the photo");
        } else {
            lblUploadSuccessful.setText("Photo Uploaded Successfully");
        }


    }//GEN-LAST:event_btnUploadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> comboGender;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmpId;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblMobile;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblTeamInfo;
    private javax.swing.JLabel lblUploadSuccessful;
    private javax.swing.JLabel lblView;
    private javax.swing.JTable tblEmployees;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmpId;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtTeamInfo;
    // End of variables declaration//GEN-END:variables

    private void populateEmployeeTable() {

        DefaultTableModel model = (DefaultTableModel) tblEmployees.getModel();

        model.setRowCount(0);

        for (Employee emp : empHistory.getEmpList()) {
            Object[] row = new Object[10];
            row[0] = emp;
            row[1] = emp.getEmpId();
            row[2] = emp.getAge();
            row[3] = emp.getGender();
            row[4] = emp.getStartDate();
            row[5] = emp.getLevel();
            row[6] = emp.getTeamInfo();
            row[7] = emp.getPositionTitle();
            row[8] = emp.getMobileNo();
            row[9] = emp.getEmail();

            model.addRow(row);

        }

    }

    private Date convertStringToDate(String startDate) throws ParseException {

        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");

        Date parsedDate = null;
        parsedDate = formatter.parse(startDate);

        return parsedDate;

    }

    private boolean validateData() {

        boolean val = true;

        if (txtName.getText().equals("")) {
            val = false;
            JOptionPane.showMessageDialog(null, "Please enter the name!");
            txtName.requestFocus();
            return false;
        } else {
            String pattern = "^[a-zA-Z]+[\\-'\\s]?[a-zA-Z ]+$";
            Pattern patternToMatch = Pattern.compile(pattern);
            Matcher match = patternToMatch.matcher(txtName.getText());
            if (!match.matches()) {
                //System.out.println("Naming is incorrect);
                JOptionPane.showMessageDialog(null, "Enter the name properly. It is Invalid");
                txtName.requestFocus();
                txtName.setText("");
                val = false;
                return false;
            }
        }

        if (txtAge.getText().equals("")) {
            val = false;
            JOptionPane.showMessageDialog(null, "Please enter the Employee Age!");
            txtAge.requestFocus();
            return false;
        } else {
            if (isNumeric(txtAge.getText()) == false) {
                JOptionPane.showMessageDialog(null, "Please enter the age in numeric format only");
                txtAge.requestFocus();
                txtAge.setText("");
                val = false;
                return false;
            } else if (Integer.parseInt(txtAge.getText()) < 21 || Integer.parseInt(txtAge.getText()) > 60) {
                JOptionPane.showMessageDialog(null, "Please enter the age in proper range which is 20 to 60 only");
                txtAge.requestFocus();
                txtAge.setText("");
                val = false;
                return false;
            }
        }

        if (txtEmpId.getText().equals("")) {
            val = false;
            JOptionPane.showMessageDialog(null, "Please enter the Employee Id!");
            txtEmpId.requestFocus();
            return false;
        } else {
            if (isNumeric(txtEmpId.getText()) == false) {
                JOptionPane.showMessageDialog(null, "Please enter the Employee ID in numeric format!");
                txtEmpId.requestFocus();
                txtEmpId.setText("");
                val = false;
                return false;
            }
        }

        if (comboGender.getSelectedItem().toString().equals("Select a value")) {
            val = false;
            JOptionPane.showMessageDialog(null, "Please select an appropriate gender ");
            return false;
        }

        if (txtStartDate.getText().equals("") && isDateValid(txtStartDate.getText()) == false) {

            val = false;

            JOptionPane.showMessageDialog(null, "Please enter the Employee Start Date!");
            txtStartDate.requestFocus();
            return false;
        } else {
            if (isDateValid(txtStartDate.getText()) == false) {
                JOptionPane.showMessageDialog(null, "Please enter the Employee Start Date in proper format dd/MM/yyyy!");
                txtStartDate.requestFocus();
                txtStartDate.setText("");
                val = false;
                return false;
            }
        }

        if (txtLevel.getText().equals("")) {
            val = false;
            JOptionPane.showMessageDialog(null, "Please enter the Employee Level!");
            txtLevel.requestFocus();
            return false;
        } else if (txtTeamInfo.getText().equals("")) {
            val = false;
            JOptionPane.showMessageDialog(null, "Please enter the Employee Team Information!");
            txtTeamInfo.requestFocus();
            return false;
        }

        if (txtMobile.getText().equals("")) {
            val = false;
            JOptionPane.showMessageDialog(null, "Please enter the Mobile number!");
            txtMobile.requestFocus();
            return false;
        } else {

            String patternPhone = "^[0-9]{0,10}$";

            Pattern phonePatternToMatch = Pattern.compile(patternPhone);
            Matcher matchPhone = phonePatternToMatch.matcher(txtMobile.getText());

            if (!matchPhone.matches()) {
                JOptionPane.showMessageDialog(null, "Invalid Phone number!");
                val = false;
                txtMobile.requestFocus();
                txtMobile.setText("");
                return false;
            } else if (txtMobile.getText().length() != 10) {
                JOptionPane.showMessageDialog(null, "Please enter a valid 10 digit mobile number");
                val = false;
                txtMobile.requestFocus();
                txtMobile.setText("");
                return false;
            }
        }

        if (txtEmail.getText().equals("")) {

            val = false;
            JOptionPane.showMessageDialog(null, "Please enter the Email Address!");
            txtEmail.requestFocus();
            return false;
        } else {
            if (emailValidation(txtEmail.getText()) == false) {
                JOptionPane.showMessageDialog(null, "Invalid email ID ");
                val = false;
                txtEmail.requestFocus();
                txtEmail.setText("");
                return false;
            }
        }

        if (txtPosition.getText().equals("")) {
            val = false;
            JOptionPane.showMessageDialog(null, "Please enter the Employee Position!");
            txtPosition.requestFocus();
            return false;
        }

        return val;

    }

    private boolean isNumeric(String value) {

        if (value == null || value == "") {
            return false;
        }
        try {
            int temp = Integer.parseInt(value);

        } catch (NumberFormatException nfe) {
            return false;
        }
        return true;

    }

    private boolean isDateValid(String startDate) {

        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        formatter.setLenient(false);
        Date parsedDate = null;
        try {
            parsedDate = formatter.parse(startDate);

        } catch (ParseException e) {
            //Handle exception
            return false;
        }
        return true;
    }

    private boolean emailValidation(String email) {

        String pattern
                = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        Pattern patternToMatch = Pattern.compile(pattern);
        Matcher match = patternToMatch.matcher(email);

        if (!match.matches()) {

            return false;
        }
        return true;

    }

    public void clearAllTextFields() {
        txtName.setText("");
        txtAge.setText("");
        txtEmail.setText("");
        txtEmpId.setText("");
        txtStartDate.setText("");
        txtLevel.setText("");
        txtTeamInfo.setText("");
        txtMobile.setText("");
        txtEmail.setText("");
        txtPosition.setText("");
        comboGender.setSelectedIndex(0);
        lblUploadSuccessful.setText("");
    }

    private void SetProfilePhoto(String photo) {
        Image img = Toolkit.getDefaultToolkit().createImage(photo);
        img = img.getScaledInstance(lblPhoto.getWidth(), lblPhoto.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(img);
        lblPhoto.setIcon(icon);
    }

}
